ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

include $(MKFILES_ROOT)/qmacros.mk
-include $(PROJECT_ROOT)/roots.mk

INSTALLDIR = sbin

LIBS = i2c-master drvr secpol

USEFILE=$(PROJECT_ROOT)/$(SECTION)/Usemsg

-include $(SECTION_ROOT)/extra.mk
include $(SECTION_ROOT)/pinfo.mk


#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk
