/*
 * Copyright (c) 2016, 2022-2023, BlackBerry Limited.
 * Copyright 2016, Freescale Semiconductor, Inc.
 * Copyright 2017, 2019, 2023 NXP
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You
 * may not reproduce, modify or distribute this software except in
 * compliance with the License. You may obtain a copy of the License
 * at: http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OF ANY KIND, either express or implied.
 *
 * This file may contain contributions from others, either as
 * contributors under the License or as licensors under other terms.
 * Please review this entire file for other proprietary rights or license
 * notices, as well as the QNX Development Suite License Guide at
 * http://licensing.qnx.com/license-guide/ for other information.
 */

#include <startup.h>
#include "board.h"
#include <soc/nxp/imx8/common/imx_gpio.h>
#include <soc/nxp/imx8/mp/mx8mp_iomux.h>
#include "imx_startup.h"
#include "nitrogen8mp_cpu.h"

/**
 * i.MX startup source file.
 *
 * @file       init_pads.c
 * @addtogroup startup
 * @{
 */

/** Definition of PADS alternate functions */
#define IMX_PAD_ALT_0   0   /**< PAD alternate function 0 */
#define IMX_PAD_ALT_1   1   /**< PAD alternate function 1 */
#define IMX_PAD_ALT_2   2   /**< PAD alternate function 2 */
#define IMX_PAD_ALT_3   3   /**< PAD alternate function 3 */
#define IMX_PAD_ALT_4   4   /**< PAD alternate function 3 */

#if IMX_NAND_INIT_ENABLED
extern bool nand_enable;
#endif


#if IMX_DEBUG
/**
 * Delay function.
 *
 * @param   timeout - number of NOP instructions to be executed.
 */
void imx_delay(uint32_t timeout)
{
    while (timeout--) {
        __asm__ __volatile__("nop");
    }
}
#endif

#if IMX_USDHC_INIT_ENABLED
/**
 * Routes and configures electrical properties of PADs for SDIO.
 *
 * @return Execution status.
 */
static int imx_init_usdhc1_pads(void)
{
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD1_CLK), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD1_CLK), IMX_PAD_CTL_SRE_FAST | IMX_PAD_CTL_DSE_2X);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD1_CMD), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD1_CMD), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP | IMX_PAD_CTL_SRE_FAST | IMX_PAD_CTL_DSE_2X);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD1_DATA0), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD1_DATA0), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP | IMX_PAD_CTL_SRE_FAST | IMX_PAD_CTL_DSE_2X);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD1_DATA1), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD1_DATA1), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP | IMX_PAD_CTL_SRE_FAST | IMX_PAD_CTL_DSE_2X);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD1_DATA2), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD1_DATA2), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP | IMX_PAD_CTL_SRE_FAST | IMX_PAD_CTL_DSE_2X);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD1_DATA3), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD1_DATA3), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP | IMX_PAD_CTL_SRE_FAST | IMX_PAD_CTL_DSE_2X);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD1_DATA4), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD1_DATA4), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP | IMX_PAD_CTL_SRE_FAST | IMX_PAD_CTL_DSE_2X);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD1_DATA5), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD1_DATA5), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP | IMX_PAD_CTL_SRE_FAST | IMX_PAD_CTL_DSE_2X);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD1_DATA6), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD1_DATA6), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP | IMX_PAD_CTL_SRE_FAST | IMX_PAD_CTL_DSE_2X);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD1_DATA7), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD1_DATA7), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP | IMX_PAD_CTL_SRE_FAST | IMX_PAD_CTL_DSE_2X);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD1_STROBE), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD1_STROBE), IMX_PAD_CTL_SRE_FAST | IMX_PAD_CTL_DSE_2X);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD1_RESET_B), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD1_RESET_B), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP);

    return 0;
}

/**
 * Routes and configures electrical properties of PADs for micro SD card slot.
 *
 * @return Execution status.
 */
static int imx_init_usdhc2_pads(void)
{
    /* GPIO2_IO12 */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD2_CD_B), IMX_MUX_CTL_MUX_MODE_ALT5);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD2_CD_B), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP | IMX_PAD_CTL_SRE_FAST | IMX_PAD_CTL_DSE_6X);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD2_CLK), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD2_CLK), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_HYS_SCHMITT | IMX_PAD_CTL_SRE_FAST);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD2_CMD), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD2_CMD), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP | IMX_PAD_CTL_HYS_SCHMITT | IMX_PAD_CTL_SRE_FAST);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD2_DATA0), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD2_DATA0), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP | IMX_PAD_CTL_HYS_SCHMITT | IMX_PAD_CTL_SRE_FAST);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD2_DATA1), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD2_DATA1), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP | IMX_PAD_CTL_HYS_SCHMITT | IMX_PAD_CTL_SRE_FAST);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD2_DATA2), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD2_DATA2), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP | IMX_PAD_CTL_HYS_SCHMITT | IMX_PAD_CTL_SRE_FAST);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD2_DATA3), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD2_DATA3), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP | IMX_PAD_CTL_HYS_SCHMITT | IMX_PAD_CTL_SRE_FAST);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SD2_RESET_B), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SD2_RESET_B), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP);

    return 0;
}

/**
 * Routes and configures electrical properties of PADSs for eMMC device.
 *
 * @return Execution status.
 */
static int imx_init_usdhc3_pads(void)
{
    /* DATA0 */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_NAND_DATA04), IMX_MUX_CTL_MUX_MODE_ALT2);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_NAND_DATA04), IMX8MP_PAD_SETTINGS_USDHC);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_USDHC3_DAT0_IN_SELECT_INPUT), 1);
    /* DATA1 */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_NAND_DATA05), IMX_MUX_CTL_MUX_MODE_ALT2);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_NAND_DATA05), IMX8MP_PAD_SETTINGS_USDHC);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_USDHC3_DAT1_IN_SELECT_INPUT), 1);
    /* DATA2 */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_NAND_DATA06), IMX_MUX_CTL_MUX_MODE_ALT2);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_NAND_DATA06), IMX8MP_PAD_SETTINGS_USDHC);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_USDHC3_DAT2_IN_SELECT_INPUT), 1);
    /* DATA3 */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_NAND_DATA07), IMX_MUX_CTL_MUX_MODE_ALT2);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_NAND_DATA07), IMX8MP_PAD_SETTINGS_USDHC);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_USDHC3_DAT3_IN_SELECT_INPUT), 1);
    /* CLK */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_NAND_WE_B), IMX_MUX_CTL_MUX_MODE_ALT2 | IMX_MUX_CTL_SION);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_NAND_WE_B), IMX_PAD_CTL_SRE_FAST | IMX_PAD_CTL_DSE_2X);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_USDHC3_CARD_CLK_IN_SELECT_INPUT), 1);
    /* CMD */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_NAND_WP_B), IMX_MUX_CTL_MUX_MODE_ALT2);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_NAND_WP_B), IMX8MP_PAD_SETTINGS_USDHC);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_USDHC3_CMD_IN_SELECT_INPUT), 1);

    return 0;
}
#endif

#if IMX_NAND_INIT_ENABLED
/**
 * NAND mux and electrical properties.
 *
 * @return Execution status.
 */
static int imx_init_nand_pads(void)
{
    return 0;
}
#endif

#if IMX_ECSPI_INIT_ENABLED
/**
 * ECSPI mux and electrical properties.
 *
 * @return Execution status.
 */
static int imx_init_ecspi_pads(void)
{
    /* ECSPI 1 */
    /* CLK */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ECSPI1_SCLK), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_ECSPI1_CSPI_CLK_IN_SELECT_INPUT), 1);
    /* MOSI */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ECSPI1_MOSI), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_ECSPI1_MOSI_SELECT_INPUT), 1);
    /* MISO */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ECSPI1_MISO), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_ECSPI1_MISO_SELECT_INPUT), 1);
    /* CS */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ECSPI1_SS0), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_ECSPI1_SS_B_SELECT_INPUT_0), 1);

    /* ECSPI 2 */
    /* CLK */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ECSPI2_SCLK), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_ECSPI2_CSPI_CLK_IN_SELECT_INPUT), 1);
    /* MOSI */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ECSPI2_MOSI), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_ECSPI2_MOSI_SELECT_INPUT), 1);
    /* MISO */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ECSPI2_MISO), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_ECSPI2_MISO_SELECT_INPUT), 1);
    /* CS */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ECSPI2_SS0), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_ECSPI2_SS_B_SELECT_INPUT_0), 1);

    return 0;
}
#endif

#if IMX_QSPI_INIT_ENABLED
/**
 * FLEXSPI mux and electrical properties.
 *
 * @return Execution status.
 */
static int imx_init_qspi_pads(void)
{
    return 0;
}
#endif

#if IMX_USB_INIT_ENABLED
/**
 * Route and configure electrical properties of PINs for USB devices.
 *
 * @return Execution status.
 */
static int imx_init_usb_pads(void)
{
    /* Configure USB1 over-current - USB1_OC */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_GPIO1_IO13), IMX_MUX_CTL_MUX_MODE_ALT1);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_GPIO1_IO13), IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP);

    /* Configure USB2 hub reset - GPIO3_IO6 */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_NAND_DATA00), IMX_MUX_CTL_MUX_MODE_ALT5);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_NAND_DATA00), IMX_PAD_CTL_PE_PULL_ENABLED);
    out32(IMX_GPIO3_BASE + IMX_GPIO_DR,   in32(IMX_GPIO3_BASE + IMX_GPIO_DR)   & ~(1 << 6U)); /* Set the pad to the low level */
    out32(IMX_GPIO3_BASE + IMX_GPIO_GDIR, in32(IMX_GPIO3_BASE + IMX_GPIO_GDIR) |  (1 << 6U)); /* Set output direction */
    imx_usleep(10 * 1000);
    out32(IMX_GPIO3_BASE + IMX_GPIO_DR,   in32(IMX_GPIO3_BASE + IMX_GPIO_DR)   |  (1 << 6U)); /* Set the pad to the high level */

    return 0;
}
#endif

#if IMX_I2C_INIT_ENABLED
/**
 * Route and configure electrical properties of pads for I2C devices.
 * NOTE: Called from imx_init_clocks.c module
 *
 * @return Execution status.
 */
int imx_init_i2c_pads(void)
{
#if IMX_I2C1_INIT_ENABLED
    /* I2C1 */
    /* SDA */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_I2C1_SDA), IMX_MUX_CTL_SION | IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_I2C1_SDA), IMX8MP_PAD_SETTINGS_I2C);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_I2C1_SDA_IN_SELECT_INPUT), 2);
    /* SCL */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_I2C1_SCL), IMX_MUX_CTL_SION | IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_I2C1_SCL), IMX8MP_PAD_SETTINGS_I2C);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_I2C1_SCL_IN_SELECT_INPUT), 2);
#endif

#if IMX_I2C2_INIT_ENABLED
    /* I2C2 */
    /* SDA */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_I2C2_SDA), IMX_MUX_CTL_SION | IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_I2C2_SDA), IMX8MP_PAD_SETTINGS_I2C);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_I2C2_SDA_IN_SELECT_INPUT), 2);
    /* SCL */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_I2C2_SCL), IMX_MUX_CTL_SION |  IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_I2C2_SCL), IMX8MP_PAD_SETTINGS_I2C);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_I2C2_SCL_IN_SELECT_INPUT), 2);
#endif

#if IMX_I2C3_INIT_ENABLED
    /* I2C3 */
    /* SDA */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_I2C3_SDA), IMX_MUX_CTL_SION | IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_I2C3_SDA), IMX8MP_PAD_SETTINGS_I2C);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_I2C3_SDA_IN_SELECT_INPUT), 4);
    /* SCL */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_I2C3_SCL), IMX_MUX_CTL_SION | IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_I2C3_SCL), IMX8MP_PAD_SETTINGS_I2C);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_I2C3_SCL_IN_SELECT_INPUT), 4);
#endif

#if IMX_I2C4_INIT_ENABLED
    /* I2C4 */
    /* SDA */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_I2C4_SDA), IMX_MUX_CTL_SION | IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_I2C4_SDA), IMX8MP_PAD_SETTINGS_I2C);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_I2C4_SDA_IN_SELECT_INPUT), 5);
    /* SCL */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_I2C4_SCL), IMX_MUX_CTL_SION | IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_I2C4_SCL), IMX8MP_PAD_SETTINGS_I2C);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_I2C4_SCL_IN_SELECT_INPUT), 5);
#endif

#if IMX_I2C5_INIT_ENABLED
    /* SDA */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SPDIF_TX), IMX_MUX_CTL_SION | IMX_MUX_CTL_MUX_MODE_ALT2);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SPDIF_TX), IMX8MP_PAD_SETTINGS_I2C);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_I2C5_SDA_IN_SELECT_INPUT), 2);
    /* SCL */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SPDIF_RX), IMX_MUX_CTL_SION | IMX_MUX_CTL_MUX_MODE_ALT2);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SPDIF_TX), IMX8MP_PAD_SETTINGS_I2C);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_I2C5_SCL_IN_SELECT_INPUT), 2);
#endif

#if IMX_I2C6_INIT_ENABLED
    /* SDA */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI5_RXC), IMX_MUX_CTL_SION | IMX_MUX_CTL_MUX_MODE_ALT3);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI5_RXC), IMX8MP_PAD_SETTINGS_I2C);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_I2C6_SDA_IN_SELECT_INPUT), 1);
    /* SCL */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI5_RXFS), IMX_MUX_CTL_SION | IMX_MUX_CTL_MUX_MODE_ALT3);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI5_RXFS), IMX8MP_PAD_SETTINGS_I2C);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_I2C6_SCL_IN_SELECT_INPUT), 1);
#endif

    return 0;
}
#endif

#if IMX_AUDIO_INIT_ENABLED
/**
 * Route and configure electrical properties of PADs for audio devices.
 *
 * @return Execution status.
 */
#define SAI_PAD_CFG (IMX_PAD_CTL_DSE_4X | IMX_PAD_CTL_SRE_FAST)

static int imx_init_audio_pads(void)
{
    /* TODO SAI2 for M2 connector */

    /* SAI3 is used with WM8960 audio codec */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI3_TXFS), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI3_TXC),  IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI3_TXD),  IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI3_RXD),  IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI3_MCLK), IMX_MUX_CTL_MUX_MODE_ALT0);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI3_TXFS), SAI_PAD_CFG);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI3_TXC),  SAI_PAD_CFG);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI3_RXD),  SAI_PAD_CFG | IMX_PAD_CTL_PE_PULL_ENABLED);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI3_TXD),  SAI_PAD_CFG);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI3_MCLK), SAI_PAD_CFG);

    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_AUDIOMIX_SAI3_MCLK_SELECT_INPUT), 2);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_AUDIOMIX_SAI3_RXDATA_SELECT_INPUT_0), 1);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_AUDIOMIX_SAI3_TXBCLK_SELECT_INPUT), 1);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_AUDIOMIX_SAI3_TXSYNC_SELECT_INPUT), 1);

    /* GPIO4 pin 29 is used to enable AUD_PWR_EN - WM8960 speakers */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI3_RXC), IMX_MUX_CTL_MUX_MODE_ALT5);
    out32(IMX_GPIO4_BASE + IMX_GPIO_DR,   in32(IMX_GPIO4_BASE + IMX_GPIO_DR)   | (1 << 29U)); /* Set the pad to the high level */
    out32(IMX_GPIO4_BASE + IMX_GPIO_GDIR, in32(IMX_GPIO4_BASE + IMX_GPIO_GDIR) | (1 << 29U)); /* Set output direction */

    return 0;
}
#endif

#if IMX_ENET_INIT_ENABLED
/**
 * Function performs configuration of the ENET0 (QoS) pads.
 *
 * @return Execution status.
 */
static int imx_init_enet0_pads(void)
{
    {
        /* ENET_TXC: mux 0 (default) */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ENET_TXC), IMX_MUX_CTL_MUX_MODE_ALT0);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_ENET_TXC), 0x1F);
        /* ENET_TD0: mux 0 (default) */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ENET_TD0), IMX_MUX_CTL_MUX_MODE_ALT0);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_ENET_TD0), 0x1F);
        /* ENET_TD1: mux 0 (default) */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ENET_TD1), IMX_MUX_CTL_MUX_MODE_ALT0);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_ENET_TD1), 0x1F);
        /* ENET_TD2: mux 0 (default) */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ENET_TD2), IMX_MUX_CTL_MUX_MODE_ALT0);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_ENET_TD2), 0x1F);
        /* ENET_TD3: mux 0 (default) */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ENET_TD3), IMX_MUX_CTL_MUX_MODE_ALT0);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_ENET_TD3), 0x1F);
        /* ENET_TX_CTL: mux 0 (default) */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ENET_TX_CTL), IMX_MUX_CTL_MUX_MODE_ALT0);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_ENET_TX_CTL), 0x1F);
    }
    {
        /* ENET_RXC: mux 0 (default) */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ENET_RXC), IMX_MUX_CTL_MUX_MODE_ALT0);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_ENET_RXC), 0x91 | IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP);
        /* ENET_RD0: mux 0 (default) */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ENET_RD0), IMX_MUX_CTL_MUX_MODE_ALT0);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_ENET_RD0), 0x91 | IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP);
        /* ENET_RD1: mux 0 (default) */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ENET_RD1), IMX_MUX_CTL_MUX_MODE_ALT0);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_ENET_RD1), 0x91 | IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP);
        /* ENET_RD2: mux 0 (default) */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ENET_RD2), IMX_MUX_CTL_MUX_MODE_ALT0);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_ENET_RD2), 0x91 | IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP);
        /* ENET_RD3: mux 0 (default) */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ENET_RD3), IMX_MUX_CTL_MUX_MODE_ALT0);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_ENET_RD3), 0x91 | IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP);
        /* ENET_RX_CTL: mux 0 (default) */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ENET_RX_CTL), IMX_MUX_CTL_MUX_MODE_ALT0);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_ENET_RX_CTL), 0x91 | IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP);
    }
    {
        /* ENET_MDC:*/
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ENET_MDC), IMX_MUX_CTL_MUX_MODE_ALT0);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_ENET_MDC), 0);
        /* ENET_MDIO */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_ENET_MDIO), IMX_MUX_CTL_MUX_MODE_ALT0);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_ENET_MDIO), 0xa0);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_ENET_QOS_GMII_MDI_I_SELECT_INPUT), 0x01);
    }

    /* Configure NAND_READY_B as GPIO3_IO16 to control ENET Reset pin*/
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_NAND_READY_B), IMX_MUX_CTL_MUX_MODE_ALT5);
    out32(IMX_GPIO3_BASE + IMX_GPIO_DR,   in32(IMX_GPIO3_BASE + IMX_GPIO_DR)   & ~(1 << 16U)); /* Set the pad to the low level */
    out32(IMX_GPIO3_BASE + IMX_GPIO_GDIR, in32(IMX_GPIO3_BASE + IMX_GPIO_GDIR) | (1 << 16U)); /* Set output direction */
    imx_usleep(10 * 1000);
    out32(IMX_GPIO3_BASE + IMX_GPIO_DR,   in32(IMX_GPIO3_BASE + IMX_GPIO_DR)   | (1 << 16U)); /* Set the pad to the high level */

    return 0;
}

/**
 * Function performs configuration of the ENET1 (FEC) pads.
 *
 * @return Execution status.
 */
static int imx_init_enet1_pads(void)
{
    {
        /* ENET_TXC: mux 4 */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI1_TXD5), IMX_MUX_CTL_MUX_MODE_ALT4);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI1_TXD5), 0x1F);
        /* ENET_TD0: mux 4 */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI1_TXD0), IMX_MUX_CTL_MUX_MODE_ALT4);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI1_TXD0), 0x1F);
        /* ENET_TD1: mux 4 */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI1_TXD1), IMX_MUX_CTL_MUX_MODE_ALT4);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI1_TXD1), 0x1F);
        /* ENET_TD2: mux 4 */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI1_TXD2), IMX_MUX_CTL_MUX_MODE_ALT4);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI1_TXD2), 0x1F);
        /* ENET_TD3: mux 4 */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI1_TXD3), IMX_MUX_CTL_MUX_MODE_ALT4);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI1_TXD3), 0x1F);
        /* ENET_TX_CTL: mux 4 */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI1_TXD4), IMX_MUX_CTL_MUX_MODE_ALT4);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI1_TXD4), 0x1F);
    }
    {
        /* ENET_RXC: mux 4 */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI1_TXC), IMX_MUX_CTL_MUX_MODE_ALT4);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI1_TXC), 0x91 | IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP);
        /* ENET_RD0: mux 4 */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI1_RXD4), IMX_MUX_CTL_MUX_MODE_ALT4);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI1_RXD4), 0x91 | IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_ENET1_RXDATA_0_SELECT_INPUT), 1);
        /* ENET_RD1: mux 4 */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI1_RXD5), IMX_MUX_CTL_MUX_MODE_ALT4);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI1_RXD5), 0x91 | IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_ENET1_RXDATA_1_SELECT_INPUT), 1);
        /* ENET_RD2: mux 4 */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI1_RXD6), IMX_MUX_CTL_MUX_MODE_ALT4);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI1_RXD6), 0x91 | IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP);
        /* ENET_RD3: mux 4 */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI1_RXD7), IMX_MUX_CTL_MUX_MODE_ALT4);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI1_RXD7), 0x91 | IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP);
        /* ENET_RX_CTL: mux 4 */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI1_TXFS), IMX_MUX_CTL_MUX_MODE_ALT4);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI1_TXFS), 0x91 | IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_PUE_PULL_UP);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_ENET1_RXEN_SELECT_INPUT), 1);
    }
    {
        /* ENET_MDC: mux 4 */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI1_RXD2), IMX_MUX_CTL_MUX_MODE_ALT4);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI1_RXD2), 0x0);
        /* ENET_MDIO: mux 4 */
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI1_RXD3), IMX_MUX_CTL_MUX_MODE_ALT4);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI1_RXD3), 0xa0);
        out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_ENET1_MDIO_SELECT_INPUT), 0x01);
    }

    /* Configure GPIO1_IO12 to control ENET Reset pin*/
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_GPIO1_IO12), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_GPIO1_BASE + IMX_GPIO_DR,   in32(IMX_GPIO1_BASE + IMX_GPIO_DR)   & ~(1 << 12U)); /* Set the pad to the high level */
    out32(IMX_GPIO1_BASE + IMX_GPIO_GDIR, in32(IMX_GPIO1_BASE + IMX_GPIO_GDIR) | (1 << 12U)); /* Set output direction */
    imx_usleep(10 * 1000);
    out32(IMX_GPIO1_BASE + IMX_GPIO_DR,   in32(IMX_GPIO1_BASE + IMX_GPIO_DR)   | (1 << 12U)); /* Set the pad to the high level */

    return 0;
}
#endif

#if IMX_FLEXCAN_INIT_ENABLED
/**
 * Routes and configures electrical properties of PADs for FlexCAN devices.
 *
 * @return Execution status.
 */
static int imx_init_flexcan_pads(void)
{
    /* CAN1 */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI5_RXD1), IMX_MUX_CTL_MUX_MODE_ALT6);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI5_RXD1), 0x154);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI5_RXD2), IMX_MUX_CTL_MUX_MODE_ALT6);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI5_RXD2), 0x154);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_CAN1_CANRX_SELECT_INPUT), 0x00);

    /* CAN2 */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI5_RXD3), IMX_MUX_CTL_MUX_MODE_ALT6);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI5_RXD3), 0x154);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI5_MCLK), IMX_MUX_CTL_MUX_MODE_ALT6);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI5_MCLK), 0x154);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_CAN2_CANRX_SELECT_INPUT), 0x00);

    return 0;
}
#endif

#if IMX_UART_INIT_ENABLED
/**
 * Routes and configures electrical properties of PADs for UART devices.
 *
 * @return Execution status.
 */
static int imx_init_uart_pads(void)
{
    /* UART2 (SER1) already configured by bootloader */

    /* UART3 (SER2) */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_NAND_CE0_B), IMX_MUX_CTL_MUX_MODE_ALT4);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_NAND_CE0_B), 0x140);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_NAND_ALE), IMX_MUX_CTL_MUX_MODE_ALT4);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_NAND_ALE), 0x140);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_UART3_UART_RXD_MUX_SELECT_INPUT), 0x02);

    /* UART4 (SER0) */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_UART4_RXD), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_UART4_RXD), 0x140);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_UART4_UART_RXD_MUX_SELECT_INPUT), 0x08);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_UART4_TXD), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_UART4_TXD), 0x140);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_NAND_DATA02), IMX_MUX_CTL_MUX_MODE_ALT3);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_NAND_DATA02), 0x140);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_NAND_DATA03), IMX_MUX_CTL_MUX_MODE_ALT3);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_NAND_DATA03), 0x140);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_INPUTx(IMX_IOMUXC_UART4_UART_RTS_B_SELECT_INPUT), 0x01);

    return 0;
}
#endif

#if IMX_GPIO_INIT_ENABLED
/**
 * Routes and configures electrical properties of PADs for GPIO.
 *
 * @return Execution status.
 */
static int imx_init_gpio_pads(void)
{
    /* Set LVDS_EN(GPIO1_IO10) to high level TODO LCD1_BACK S107 & DISP_PWM1 S122 */
    out32(IMX_GPIO1_BASE + IMX_GPIO_DR,
                                       (in32(IMX_GPIO1_BASE + IMX_GPIO_DR) |
                                       (0x01 << 10)));
    /* Set LVDS_EN(GPIO1_IO10) direction to output */
    out32(IMX_GPIO1_BASE + IMX_GPIO_GDIR,
                                         (in32(IMX_GPIO1_BASE + IMX_GPIO_GDIR) |
                                         (0x01 << 10)));

    /* Set I2C expander reset signal high */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_NAND_DATA01),
	  IMX_MUX_CTL_MUX_MODE_ALT5);
    out32(IMX_GPIO3_BASE + IMX_GPIO_DR,   in32(IMX_GPIO3_BASE + IMX_GPIO_DR)   |  (1 << 7U));
    out32(IMX_GPIO3_BASE + IMX_GPIO_GDIR, in32(IMX_GPIO3_BASE + IMX_GPIO_GDIR) |  (1 << 7U));

    /* Set GPIO expander reset signal high */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI2_MCLK),
          IMX_MUX_CTL_MUX_MODE_ALT5);
    out32(IMX_GPIO4_BASE + IMX_GPIO_DR,   (in32(IMX_GPIO4_BASE + IMX_GPIO_DR)   | (1 << 27)));
    out32(IMX_GPIO4_BASE + IMX_GPIO_GDIR, (in32(IMX_GPIO4_BASE + IMX_GPIO_GDIR) | (1 << 27)));

    /* Set GPIO expander irq signal, pull-up / input */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI2_RXC),
          IMX_MUX_CTL_MUX_MODE_ALT5);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI2_RXC),
          IMX_PAD_CTL_PE_PULL_ENABLED | IMX_PAD_CTL_HYS_CMOS | IMX_PAD_CTL_PUE_PULL_UP);
    out32(IMX_GPIO4_BASE + IMX_GPIO_GDIR, (in32(IMX_GPIO4_BASE + IMX_GPIO_GDIR) & ~(1 << 22)));

    return 0;
}
#endif

#if IMX_PCIE_INIT_ENABLED
/**
 * Routes and configures electrical properties of PADs for PCIe.
 *
 * @return Execution status.
 */
static int imx_init_pcie_pads(void)
{
    /* Configure SAI3_RXFS as GPIO to control PCIe nWAKE pin */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_SAI3_RXFS), IMX_MUX_CTL_MUX_MODE_ALT5);
    out32(IMX_GPIO5_BASE + IMX_GPIO_GDIR, (in32(IMX_GPIO4_BASE + IMX_GPIO_GDIR) & ~(0x01UL << 28))); /* Set input direction */
    /* Configure SAI2_RXFS as GPIO to control PCIe nPERST pin */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI2_RXFS), IMX_MUX_CTL_MUX_MODE_ALT5);
    out32(IMX_GPIO2_BASE + IMX_GPIO_DR,   (in32(IMX_GPIO4_BASE + IMX_GPIO_DR)   & ~(0x01UL << 21))); /* Set the pad to the low level */
    out32(IMX_GPIO2_BASE + IMX_GPIO_GDIR, (in32(IMX_GPIO4_BASE + IMX_GPIO_GDIR) | (0x01UL << 21))); /* Set output direction */
    /* Configure SAI1_RXFS to control PCIe nCLKREQ pin */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_SAI1_RXFS), IMX_MUX_CTL_MUX_MODE_ALT5);
    out32(IMX_GPIO2_BASE + IMX_GPIO_DR,   (in32(IMX_GPIO4_BASE + IMX_GPIO_DR)   & ~(0x01UL << 0))); /* Set the pad to the low level */
    out32(IMX_GPIO2_BASE + IMX_GPIO_GDIR, (in32(IMX_GPIO4_BASE + IMX_GPIO_GDIR) | (0x01UL << 0))); /* Set output direction */

    return 0;
}
#endif

#if IMX_MIPI_CSI_INIT_ENABLED
/**
 * Routes and configures electrical properties of PADs for MIPI CSI.
 *
 * @return Execution status.
 */
static int imx_init_mipi_csi_pads(void)
{
    return 0;
}
#endif

#if IMX_DC_INIT_ENABLED
/**
 * Route and configure electrical properties of PADs for display devices.
 *
 * @return Execution status.
 */
static int imx_init_display_pads(void)
{
    /* DSI_EN: mux 0*/
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_GPIO1_IO08), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_GPIO1_IO08),
          IMX_PAD_CTL_PE_PULL_DISABLED | IMX_PAD_CTL_HYS_CMOS | IMX_PAD_CTL_PUE_PULL_UP |
          IMX_PAD_CTL_ODE_PUSH_PULL | IMX_PAD_CTL_SRE_FAST | IMX_PAD_CTL_DSE_6X);

    /* Configure HDMI pins */
    /* DDC_SCL */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_HDMI_DDC_SCL), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_HDMI_DDC_SCL), IMX8MP_PAD_SETTINGS_I2C);
    /* DDC_SDA */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_HDMI_DDC_SDA), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_HDMI_DDC_SDA), IMX8MP_PAD_SETTINGS_I2C);
    /* CEC */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_HDMI_CEC), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_HDMI_CEC), IMX_PAD_CTL_SRE_FAST);
    /* HPD */
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_MUX_CTL_PADx(IMX_IOMUXC_SW_MUX_CTL_PAD_HDMI_HPD), IMX_MUX_CTL_MUX_MODE_ALT0);
    out32(IMX_IOMUXC_BASE + IMX_IOMUXC_SW_PAD_CTL_PADx(IMX_IOMUXC_SW_PAD_CTL_PAD_HDMI_HPD), IMX_PAD_CTL_SRE_FAST);

    return 0;
}
#endif

/**
 * Initialize peripheral pads.
 *
 * @return Execution status.
 */
int imx_init_pads(imx_startup_data_t *startup_data)
{
    do {
#if IMX_ENET_INIT_ENABLED
        /* Configure ENET0 QoS pads */
        if (imx_init_enet0_pads() != 0) {
            break;
        }
        /* Configure ENET1 FEC pads */
        if (imx_init_enet1_pads() != 0) {
            break;
        }
#endif
#if IMX_USB_INIT_ENABLED
        /* Configure USB pads */
        if (imx_init_usb_pads() != 0) {
            break;
        }
#endif
#if IMX_USDHC_INIT_ENABLED
        /* Configure USDHC1 pads */
        if (imx_init_usdhc1_pads() != 0) {
            break;
        }
        /* Configure USDHC2 pads */
        if (imx_init_usdhc2_pads() != 0) {
            break;
        }
        /* Configure USDHC3 pads */
        if (imx_init_usdhc3_pads() != 0) {
            break;
        }
#endif
#if IMX_ECSPI_INIT_ENABLED
        /* Configure ECSPI pads */
        if (imx_init_ecspi_pads() != 0) {
            break;
        }
#endif
#if IMX_QSPI_INIT_ENABLED
        /* Configure QSPI pads */
        if (imx_init_qspi_pads() != 0) {
            break;
        }
#endif
#if IMX_NAND_INIT_ENABLED
        /* Configure NAND pads */
        if (nand_enable) {
            if (imx_init_nand_pads() != 0) {
                break;
            }
        }
#endif
#if IMX_FLEXCAN_INIT_ENABLED
        /* Configure FlexCAN pads */
        if (imx_init_flexcan_pads() != 0) {
            break;
        }
#endif
#if IMX_UART_INIT_ENABLED
        /* Configure UART pads */
        if (imx_init_uart_pads() != 0) {
            break;
        }
#endif
#if IMX_AUDIO_INIT_ENABLED
        /* Configure Audio pads */
        if (imx_init_audio_pads() != 0) {
            break;
        }
#endif
#if IMX_GPIO_INIT_ENABLED
        if (imx_init_gpio_pads() != 0) {
            break;
        }
#endif
#if IMX_PCIE_INIT_ENABLED
        /* Configure PCIe pads */
        if (imx_init_pcie_pads() != 0) {
            break;
        }
#endif

#if IMX_MIPI_CSI_INIT_ENABLED
        /* Configure PCIe pads */
        if (imx_init_mipi_csi_pads() != 0) {
            break;
        }
#endif
#if IMX_DC_INIT_ENABLED
        /* Configure display related pads */
        if (imx_init_display_pads() != 0) {
            break;
        }
#endif
        return 0;
    } while (0);
    return -1;
}

/** @} */ /* End of startup */

#if defined(__QNXNTO__) && defined(__USESRCVERSION)
#include <sys/srcversion.h>
#endif
