ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

CCFLAGS += $(CCF_$(COMPILER_TYPE)_$(COMPILER_DRIVER)) \
	        $(CCFLAGS_$(SECTION))   \
	        $(CCFLAGS_$(COMPILER_TYPE)_$(CPU)) \
	        $(CCFLAGS_$(CPU))   \
	        $(CCFLAGS_$(basename $@)) \
	        $(CCFLAGS_$(basename $@)_$(CPU))\
	        -DF3S_VER=3

ROOT_PATTERNS := $(dir $(wildcard ../../*/.))
CPU_PATTERNS := $(dir $(wildcard ../../*/Makefile))
SOC_PATTERNS := $(dir $(wildcard ../../soc/*/.))

EXTRA_SRCVPATH = $(filter-out $(CPU_PATTERNS), $(ROOT_PATTERNS) $(SOC_PATTERNS))

NAME=mtd-snor

include $(MKFILES_ROOT)/qmacros.mk

# If the flash filesystem headers/libraries aren't present on the system, kill
# the compiles.
ifeq ($(call FIND_HDR_DIR,nto,usr/include,fs/f3s_spec.h),)
TARGET_BUILD=@$(ECHO_HOST) Flash filesystem headers/libraries not present on system
TARGET_INSTALL=
SRCS=
endif

# Include the SOC specific extra.mk if it exists
-include $(PROJECT_ROOT)/soc/*/extra.mk


#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk

-include $(PROJECT_ROOT)/roots.mk
