ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

include $(MKFILES_ROOT)/qmacros.mk

NAME=spi-$(SECTION)
EXTRA_SILENT_VARIANTS+=$(subst -, ,$(SECTION))

USEFILE=$(SECTION_ROOT)/$(NAME).use

TYPE = $(firstword $(filter a o dll, $(VARIANTS)) o)
CCFLAGS += $(CCFLAGS_$(SECTION)_$(CPU))

CCFLAGS += -fstack-protector-strong -fPIC -D_FORTIFY_SOURCE=2 -Wtrampolines -Wall -Wformat=2 -Werror=format-extra-args
LDFLAGS += -Wl,-z,relro -Wl,-z,now

LIBS += io-spi slog2 secpol

include $(SECTION_ROOT)/extra.mk
include $(SECTION_ROOT)/pinfo.mk


#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk

-include $(PROJECT_ROOT)/roots.mk