ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

define PINFO
PINFO DESCRIPTION=GPIO Resource Manager
endef

NAME := gpio
EXTRA_SILENT_VARIANTS = $(subst -, ,$(SECTION))
USEFILE = $(PROJECT_ROOT)/$(PRODUCT).use
INSTALLDIR = bin
LIBS += slog2 secpol login

ifdef FORTIFY_LEVEL_SUPPORTED
FORTIFY_LEVEL := 2
else
CCFLAGS += -D_FORTIFY_SOURCE=2
endif

ifneq ($(QNX_ALLOW_WERROR), 0)
CCFLAGS += -Werror
endif
CCFLAGS += -Wall -Wextra -Wconversion -Wsign-conversion -Wno-deprecated-declarations -Wmissing-prototypes -Wformat=2 -Wno-format-nonliteral

include $(MKFILES_ROOT)/qmacros.mk

#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk

